server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: dns
    static_configs:
      - targets: [localhost]
        labels:
          job: dns
          source: pihole
          __path__: /var/log/hsl/dns/*.log

  - job_name: zeek
    static_configs:
      - targets: [localhost]
        labels:
          job: zeek
          source: zeek
          __path__: /var/log/hsl/zeek/*.log

  - job_name: suricata
    static_configs:
      - targets: [localhost]
        labels:
          job: suricata
          source: suricata
          __path__: /var/log/hsl/suricata/*.log
