version: "3.9"

services:
  loki:
    image: grafana/loki:3.2.1
    container_name: hsl-loki
    command: ["-config.file=/etc/loki/local-config.yaml"]
    ports:
      - "3100:3100"
    volumes:
      - ../configs/loki-config.yml:/etc/loki/local-config.yaml:ro

  promtail:
    image: grafana/promtail:3.2.1
    container_name: hsl-promtail
    command: ["-config.file=/etc/promtail/config.yml"]
    volumes:
      - ../configs/promtail-config.yml:/etc/promtail/config.yml:ro
      - ../../logs:/var/log/hsl:ro
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:11.2.0
    container_name: hsl-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - loki

volumes:
  grafana-data:
